version: "3.8"
services:
  database:
    container_name: project_db
    image: 'mysql'
    restart: unless-stopped
    ports:
      - '3307:3306'
    expose:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'category_and_product'
      MYSQL_ROOT_PASSWORD: 'root'
  service:
    container_name: project_api
    build:
#      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: on-failure
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/category_and_product"

